### ISSUE TITLE
Incorrect Polygon Decomposition (Snoeyink-Keil)

### ISSUE THREAD

**Issue by voces** [azrafe7/hxGeomAlgo#11]
Compiled to JavaScript and the following polygon is decomposing incorrectly:

    [   {x: 0,   y: 0},
        {x: 300, y: 280},
        {x: 200, y: 300},
        {x: 150, y: 350},
        {x: 0,   y: 400},
        {x: 400, y: 400},
        {x: 400, y: 0}     ]

One of the resulting sub-polygons seems to be missing the corner vertex. In the following image, the red represents the original polygon while the purple represents new polygons:

![Example image](https://i.imgur.com/uV1kcTf.png)

**Comment by azrafe7** [comment]
Definitely a bug, thanks for reporting it!

Not sure yet if my port is faulty, or there's a problem in the original implementation (http://www.cs.ubc.ca/~snoeyink/demos/convdecomp/MCDDemo.html). In any case it's not going to be easy to track it down.

Can you please try if preprocessing your polys so that the first vertex is always the top-right-most one makes it work correctly? 

(meaning something like this)
```haxe
	var testPoly = [
		{x: 0,   y: 0},
		{x: 300, y: 280},
		{x: 200, y: 300},
		{x: 150, y: 350},
		{x: 0,   y: 400},
		{x: 400, y: 400},
		{x: 400, y: 0 }
	];
	
	var topRightIdx = 0;
	var p = testPoly[0];
	for (i in 1...testPoly.length) {
		var q = testPoly[i];
		if (q.y < p.y || (q.y == p.y && q.x > p.x)) {
			topRightIdx = i;
			p = q;
		}
	}
	if (topRightIdx != 0) {
		var newTail = testPoly.splice(0, topRightIdx);
		testPoly = testPoly.concat(newTail);
	}
```

And even if that works out, I'd really appreciate if you report back and/or have any other failing cases.

Thanks!

**Comment by voces** [comment]
That did fix the provided polygon, but I found a very similar case:

    [ {x: 500, y: 0},
      {x: 0,   y: 0},
      {x: 0,   y: 500},
      {x: 200, y: 400},
      {x: 500, y: 500},
      {x: 350, y: 150},
      {x: 400, y: 100},
      {x: 200, y: 100},
      {x: 100, y: 400},
      {x: 100, y: 100}  ]

As an image:
![Image](https://i.imgur.com/IEiAN2G.png)

I believe it's the same issue. If I remove the first three and last vertex, it results in an error. If I do the same but order it as suggested (top-right first), it works fine.

**Comment by azrafe7** [comment]
I've probably found the culprit. It's on my side (not the original impl.) and involves how I'm reconstructing the polys based on the diagonals the algo finds ([around here](https://github.com/azrafe7/hxGeomAlgo/blob/23cd1731c2209de3a5e268edd1c0cb1c4395d31f/src/hxGeomAlgo/SnoeyinkKeil.hx#L391)).

Working on it... it'll require some thinking and tinkering though.

**Comment by azrafe7** [comment]
Hey @voces, I just pushed a commit that aims to fix these issues, can you please try if it works for you?

**Comment by voces** [comment]
Awesome, that fixed it. After this 1650-point test, I'm mostly convinced it works for random shapes.

![](https://i.imgur.com/N7Qpp8b.jpg)

**Comment by azrafe7** [comment]
That's great to hear! \o/ 

Please report back if you encounter any other issues with it.

Can you test if big polys like this work correctly regardless of orientation (so both in cw or ccw order)?

(As a next step I'm going to ditch my current EarClipper impl. and port the one from mapbox which seems way more robust and flexible than my current code)

**Comment by azrafe7** [comment]
For clarity I'd also add that there should be no need to "align" to the top-right vertex (was just a thing I needed for investigating the issue).

Closing this now, but please file another one if you have any more problems with it.
