### ISSUE TITLE
Selfintersecting

### ISSUE THREAD

**Issue by pshtif** [azrafe7/hxGeomAlgo#3]
Does it offer a triangulation or decomposition for selfintersecting polygons? 

Since I don't want to reinvent a wheel I am looking for a triangulation library to be used for my framework Genome2D, so far surprisingly Nape has the most robust triangulation/decomposition utilities but its too linked together to be feasible to target Flash SWC with the whole Nape library.

**Comment by pshtif** [comment]
Thanks man going to check it out, looks great from the demo the performance also seems better than Napes from a quick look.

**Comment by azrafe7** [comment]
My port of tess2.js is _much_ probably slower than the original one, but should have no problem in handling selfintersecting polys as the original.

I've also added an experimental Delaunay refinement ported from a PR in the C repo of libtess2 in case you're interested (https://github.com/memononen/libtess2/pull/7). As of now the count of tris is somewhat high (the same of the default triangulation), but their shape is considerably better.
